project:
  type: website
  output-dir: site
  preview:
    port: 4202
    browser: true
  render:
    - "*.qmd"
    - "!refs/"
  resources:
    - "img/"
    - "talks/img/"

website:
  title: "Managing Your Dissertation"
  favicon: "/img/favicon.ico"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Welcome

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    embed-resources: true
  revealjs:
    transition: slide
    transition-speed: fast
    background-transition: fade
