project:
  type: website
  output-dir: docs
  preview:
    port: 4202
  render:
    - "!refs/"
  resources:
    - "img"

website:
  title: "Managing Your Dissertation"
  image: "img/CASA_Logo_no_text.png"
  favicon: "/img/favicon.ico"
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    logo: "/img/CASA_Logo_no_text.png"
    collapse: true
    collapse-below: md
    left:
      - text: "Welcome"
        href: index.qmd

#bibliography: bib/Reades.bib
#csl: bib/chicago-author-date.csl

highlight-style: pygments

format:
  html:
    theme:
      - minty
    toc: false
  revealjs:
    #theme: default
    transition: slide
    transition-speed: fast
    background-transition: fade
